name: Run Telegram Bot with Token Check

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pyTelegramBotAPI

      - name: Debug environment variables
        run: |
          echo "Listing all environment variables:"
          env
          echo "BOT_TOKEN length: ${#BOT_TOKEN}"

      - name: Run bot script
        run: python ali_bot.py
